### ISSUE TITLE
El badge de la bandeja de correos enviados no se actualiza nunca

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Outlook#1]

**Comment by jorge9200** [comment]
parece que directamente no esta poniendo el numero de enviados correcto

**Comment by jorge9200** [comment]
bueno esperate, por que puede ser debido a que estoy usando una cuenta gmail en el cliente de outlook, esta haciendo cosas muy locas

**Comment by jorge9200** [comment]
Parece que ni siquiera se actualiza al cerrar y re-abrir la aplicación

**Comment by RJ64** [comment]
¿Cuándo se debería actualizar? Tendrá los problemas que todas las carpetas pero no hay ningún motivo especial no? Cuando envías un correo debería estar como leido

**Comment by jorge9200** [comment]
es cierto, cierro
