### ISSUE TITLE
No se muestra texto en el boton de autentificacion

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#10]
![screen shot 2017-12-15 at 18 31 47](https://user-images.githubusercontent.com/26099829/34053229-407531dc-e1c6-11e7-994f-4e4644846cd8.png)

**Comment by RJ64** [comment]
Eso es por un bug que ya le comenté a Javi. Justo has abierto cuando acababa de guardar el archivo js y por algún motivo hasta pasados unos 20 segundos no carga el js. Pasa con todos los archivos. Vuelve a probar
