### ISSUE TITLE
Faltan los badges de aplicacion

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Outlook#11]
Debe hacerse uso del api de App para setear el badge de aplicación a la suma total de las notificaciones pendientes de todas las cuentas vinculadas.

Para ello:

`api.app.setBadge(numberOfBadge);`

**Comment by RJ64** [comment]
Necesitaría más información acerca de cómo funciona

**Comment by jorge9200** [comment]
El badge es el numero que aparecerá en el boton de la aplicación en todo momento. Este indicará el numero de notificaciones totales que tenga la aplicación. Lo único que deberás hacer es mantenerlo actualizado al numero total de mensajes no leidos (conjunto de todas las cuentas activas).

Como es algo que debera actualizarse aun con la aplicacion cerrada deberá hacer uso del service.js.

Pero este siempre tendra que mostrar el numero correcto total de mensajes sin leer.

Ej:`api.app.setBadge( getUnreadMessages() )`
Ej:`api.app.setBadge( 2 )`

**Comment by RJ64** [comment]
¿Pero cómo lo hacéis? Porque no se cargan los js de todos los programas al entrar en horbito no? Para mostrar el badge correctamente tendría que pedir todas las cuentas y todas las carpetas de todas las cuentas para encontrar el inbox. Lo digo para que seáis conscientes de que se van a tener que llamar a muchas apis consumiendo muchos recursos

**Comment by RJ64** [comment]
Confírmame y lo hacemos

**Comment by jorge9200** [comment]
La idea seria hacer lo siguiente:

Usar el service.js de la app de outlook, un script que se ejecutará en segundo plano siempre. Para usarlo puedes seguir la guia que hice en esta issue:
https://github.com/Inevio/Gmail/issues/12

Introduces el script en el info.json
![image](https://user-images.githubusercontent.com/8724844/34247281-3524e4d8-e632-11e7-856e-1f32ed63f275.png)

Introduces el permiso en el info.json
![image](https://user-images.githubusercontent.com/8724844/34247294-3a3f3b08-e632-11e7-836b-42bee1a8cc1a.png)

Una vez creado el script service.js haremos lo siguiente:

En service.js pedimos las cuentas de outlook del usuario de horbito. Y dejamos preparados los listeners de los eventos. Solo desde aqui actualizaremos los badges, llevando un contador de las notificaciones totales por leer. De esta manera no habra llamadas a setBadge() replicadas y se ejecutará este la app abierta o cerrada.

**Comment by RJ64** [comment]
Hecho. Aunque yo tengo dos cuentas por ejemplo. Cuando entro en horbito a lo mejor me aparece un 8 y tarda un rato en ponerme 68 (60 de la segunda cuenta). Esto es por el problema que hay comentado en otro hilo de que a veces tarda en responder las llamadas a las apis pero está funcionando perfectamente por nuestra parte. Y se actualiza si se recibe un correo

**Comment by jorge9200** [comment]
Perfecto, lo damos por cerrado entonces y vamos a ver si conseguimos mejorar la latencia
