### ISSUE TITLE
Añadir checkboxes a la izquierda de cada email

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#12]
Screenshot del outlook original
![screen shot 2017-12-19 at 11 36 40](https://user-images.githubusercontent.com/26099829/34153097-24c3cafa-e4b1-11e7-9efb-cfd2ae320d5b.png)

**Comment by RJ64** [comment]
Los checkboxes no eran un requisito. Ni al principio ni en la revisión se comentó

**Comment by Alb3niz** [comment]
Yo acabo de entrar a la empresa y como soy de los pocos que usan el outlook, me han pedido que lo pruebe y de feedback. No lo he marcado como un bug, ni es urgente ni un requisito, pero si no se pueden seleccionar emails en la bandeja de entrada (con checkboxes o con cualquier otra cosa), para moverlos a una carpeta diferente o borrarlos hay que entrar en los emails y hacerlo uno a uno. Igual se puede implementar una vez que lo esencial esté terminado. Va teniendo buena pinta.

**Comment by Robby2023** [comment]
Aunque no sea prioritario ni estuviese en los requisitos lo vuelvo a abrir porque es una mejora a futuro que tenemos que hacer.

**Comment by RJ64** [comment]
Done

**Comment by Alb3niz** [comment]
Si perfecto, igualito que el original. Lo unico que no me funciona aun es el boton de eliminar emails seleccionados.

**Comment by Alb3niz** [comment]
Veo que el boton de eliminar los emails seleccionados ya funciona. Cierro issue
