### ISSUE TITLE
La aplicación se queda en la pantalla inicial de login

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#13]
Cuando abro la aplicación y le doy a lo que sería el botón de logearse (una barra gris de momento) no ocurre nada. Si abro la consola y vuelvo a abrir la aplicación se ve que ya tiene mi cuenta y que ha cargado mis emails. Esto es lo que se ve:

<img width="1192" alt="screen shot 2017-12-20 at 15 01 48" src="https://user-images.githubusercontent.com/26099829/34210760-48eb79d2-e597-11e7-945d-d9f94bb19d96.png">

**Comment by RJ64** [comment]
Estoy trabajando en ello y tenéis el bug en la plataforma que ya he comentado múltiples veces a varios de vosotros

**Comment by jorge9200** [comment]
@RJ64 , puedes comentar cual es el fallo exactamente? Así dejamos esta issue abierta asignada a quien corresponda para arreglarlo.

**Comment by RJ64** [comment]
Cuando modifico un archivo mediante ftp, al guardar tengo que esperar como unos 20 segundos a que se cargue. Trato de explicarme mejor: al guardar cualquier archivo cuando el filezilla me dice se ha subido correctamente recargo horbito y al abrir el programa, si he modificado el css todo me aparece desordenado porque el css está vacio, si es el javascript se me queda la página de login porque el js está vacío... Tras unos 20 segundos recargo horbito y al abrir el programa ya me los carga correctamente

Pensaba que me ocurría solo a mí pero probé con otro navegador e igual y ya la prueba definitiva fue cuando vosotros accedéis mientras yo estoy trabajando y os encontráis con este problema también

**Comment by jorge9200** [comment]
entiendo, y eso provoca tambien el que no pase a veces de la pantalla de log in?

**Comment by jorge9200** [comment]
nos lo asigno para que intentemos solucionarlo

**Comment by RJ64** [comment]
Si, porque entra cuando he debido modificar el js y entonces solo carga el html y el css y no carga ni los textos

**Comment by jorge9200** [comment]
parece que se soluciono
