### ISSUE TITLE
Issues de Editor de Texto

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#14]
Yo creo que ninguno de estos issues es crítico para lanzar la app ya que en general la gente suele utilizar sus propios editores de texto antes de mandar un email, pero bueno, para que queden marcadas.

- La función de "italic" no convierte el texto seleccionado en italic al escribir un email nuevo.

- Las funciones de "Indent" y "Outdent" provocan que el texto seleccionado pierda el formato y el espacio entre lineas cuando se usa repetidamente:

![screen shot 2018-01-08 at 16 49 13](https://user-images.githubusercontent.com/26099829/34678728-42653b50-f494-11e7-8fe1-c4e01536057c.png)
![screen shot 2018-01-08 at 16 49 46](https://user-images.githubusercontent.com/26099829/34678733-45153fc6-f494-11e7-85be-10e2ed5b0fae.png)

- Las funciones de "Ordered List" y "Unordered List" para añadir bullet points / números al texto seleccionado no hace nada.

**Comment by Alb3niz** [comment]
El texto dentro de el dropdown de tipo de letra (h1, h2, h3, etc...) está un pelín off.
![screen shot 2018-01-08 at 17 40 24](https://user-images.githubusercontent.com/26099829/34681222-77ace0ae-f49b-11e7-857e-c1f0cc53e87e.png)

**Comment by RJ64** [comment]
Comprobad que este editor vaya mejor. Es tinymce, debería. Si eso mirad si queremos quitar alguna opción

**Comment by Alb3niz** [comment]
Vale ya lo he comprobado y este funciona mucho mejor. Antes de cerrar el Issue hay un problema mas. El espacio entre lineas es demasiado grande y no veo forma de cambiarlo. Gmail usa TINYMCE y el espacio entre lineas en gmail esta bien.

![screen shot 2018-01-17 at 18 55 20](https://user-images.githubusercontent.com/26099829/35058369-06956246-fbb8-11e7-9488-e0652a17f419.png)

**Comment by RJ64** [comment]
Es css. Solucionado

**Comment by Alb3niz** [comment]
Si esta casi solucionado. Cuando salto de linea con Shift + Enter funciona pero cuando solo uso Enter el espacio entre lineas sigue siendo muy grande.

**Comment by RJ64** [comment]
Done

**Comment by Alb3niz** [comment]
Perfecto! Cierro.

**Comment by jorge9200** [comment]
Oye @RJ64 ha vuelto a pasar lo de los saltos de linea. Si le doy al Enter mete un salto enorme y si le doy Shift+Enter mete el espacio correcto.

Debería meter siempre el correcto (independientemente de usar Shift o no)

**Comment by RJ64** [comment]
Modificado el comportamiento, es lo que hace outlook pero no me parece lo correcto. En la edición de un correo un enter debería ser un nuevo párrafo como hace el thunderbird, pero bueno. Listo
