### ISSUE TITLE
Movimiento de emails entre carpetas

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#15]
Ahora mismo no hay (o no he encontrado) una manera de mover emails de una carpeta a otra (lo cual hace que la función de crear carpetas sea pointless de momento).

Nacho me ha confirmado que hay un método en la API para mover los correos de una carpeta o otra.

**Comment by RJ64** [comment]
Se pueden mover seleccionando los correos en la lista con los checkboxes. ¿Así os parece bien?

**Comment by Alb3niz** [comment]
Si, esta muy guay asi! Cierro.
