### ISSUE TITLE
No se pueden adjuntar archivos a un email nuevo

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#16]
La función de adjuntar archivos al escribir un email nuevo no funciona. Puedo usar la función y seleccionar el archivo que quiero adjuntar pero cuando le doy a seleccionar no ocurre nada.

Jorge me comenta que esto ya esta implementado y funcionando pero por el momento a mi no me funciona.

**Comment by icastillejogomez** [comment]
Cierro esta issue porque se va a solucionar junto a https://github.com/Inevio/Outlook/issues/9 

Asi evitamos duplicados.
