### ISSUE TITLE
Actualizar la bandeja de entrada

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#18]
A no ser que abra y cierre la aplicacion de outlook o actualice la pagina de Horbito, la bandeja de entrada no se actualiza en ningun momento. Lo mismo le pasa a la notificacion del icono de acceso directo que indica que hay un email nuevo.

**Comment by icastillejogomez** [comment]
Eso era debido a las notificaciones de webhook. Ya están levantadas y he comprobado que llegan eventos. @Alb3niz revisa:

>  Lo mismo le pasa a la notificación del icono de acceso directo que indica que hay un email nuevo.

Por si siguiera sucediendo.

**Comment by Alb3niz** [comment]
Perfecto! Funciona estupendo.
