### ISSUE TITLE
Bucle infinito por el websocket de eventos "integrationGenericListAccounts"

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Outlook#19]
En cuanto abres la app, empieza un bucle infinito de peticiones que salen de la app al backend de eventos "integrationGenericListAccounts"

Te dejo un video donde se ve: http://wz.io/f/MtjujZTL

**Comment by icastillejogomez** [comment]
el evento se llama `added-account` y se recibe solo si el proceso OAuth se ha completado con éxito.

![image](https://user-images.githubusercontent.com/16567802/35062031-3ce452e8-fbc3-11e7-8396-651fe6cb8393.png)

**Comment by RJ64** [comment]
Done

**Comment by icastillejogomez** [comment]
Si esta solucionado! Ahora hemos visto que hay una segunda llamada a listAccounts ¿Tiene algún sentido esa segunda llamada? ¿Se puede evitar? 

Gracias Ricardo!!

Te dejo un vídeo donde se ve: http://wz.io/f/Y4KeUaZr

**Comment by RJ64** [comment]
Sí claro. El evento added-account no me da los datos de la cuenta, sus funciones... No puedo operar en la cuenta sin todo eso
