### ISSUE TITLE
No encuentro manera de borrar una cuenta de la aplicación

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Outlook#2]
En caso de que no exista, necesitamos una. Podemos hacerla como en gmail, al hacer hover sobre la cuenta, aparece un boton para borrarla:

![image](https://user-images.githubusercontent.com/8724844/33173045-dd1eb01a-d052-11e7-83fc-565e5824218c.png)

**Comment by RJ64** [comment]
Así se borran las adicionales, ¿y la principal cómo la hago?

**Comment by jorge9200** [comment]
@RJ64 en teoria es que la principal tambien deberia mostrarse abajo, solo que en modo active. @tavi004 confirma con diseño

**Comment by tavi004** [comment]
Efectivamente, todas las cuentas deberian salir abajo. La activa debería salir en azul con un indicador a la izquierda y las inactivas en gris. Y para borrar como en gmail al hacer hover sobre la cuenta a la derecha te aparece un boton de "-"
![image](https://user-images.githubusercontent.com/3248361/33275951-66b4d036-d394-11e7-99f5-b879fb4a05a2.png)

**Comment by RJ64** [comment]
Done

**Comment by jorge9200** [comment]
no coincide con el diseño propuesto:

![image](https://user-images.githubusercontent.com/8724844/34102245-a94fabfa-e3e8-11e7-953d-69cad186efbe.png)

Por favor @tavi004 @RJ64 poneros de acuerdo para proporcionaros lo que necesitéis y dejarlo bien please

**Comment by tavi004** [comment]
El diseño no coincide @RJ64 , mira estas imágenes con guías para maquetarlo guay. El scroll debería estar mas pegado y no estar fijado, solo cuando hagas hover sobre esa zona que te salga un pequeño scroll a la derecha. 






![delete](https://user-images.githubusercontent.com/3248361/34149855-ca553130-e4a6-11e7-92a5-22da8003508e.png)
![delete 2x](https://user-images.githubusercontent.com/3248361/34149856-ca6a79dc-e4a6-11e7-9ee2-40dfcfe8febe.png)
![outlook-1](https://user-images.githubusercontent.com/3248361/34149859-cd9fbbb2-e4a6-11e7-9b14-55f4912f1d8e.png)
![outlook-2](https://user-images.githubusercontent.com/3248361/34149860-cdb6bc7c-e4a6-11e7-9b8d-dcf55c741c2b.png)

El hover debería ir hasta el final de la ventana no hasta el avatar.

**Comment by RJ64** [comment]
¿Mejor ahora?

**Comment by tavi004** [comment]
Bueno vamos a ir por partes porque todavía sigue estando mal.

- El tamaño y color del email y contador no están bien, usa los mismos que los del titulo
- Todavía falta la linea a la izquierda de la cuenta que está activa. 2px ancho y #0078d7
- Los contadores deberían ser grises, solo en el caso de que sea la cuenta activa en cuyo caso tanto el correo como el contador debe ser azul (0078d7).
- La linea separadora de arriba es muy oscura, usa d8d8d8
- En el hover de las cuentas metele 2px de padding arriba y abajo para que no acabe justo en el borde del avatar.
- Te he pasado el icono de borrar cuenta en el ultimo comentario y no lo has metido

Por favor limítate a copiar el diseño, si te hace falta algún color o algún asset pídemelo pero no lo intentes replicar o te lo inventes. Nosotros usamos una extensión de chrome que te deja añadir una imagen del diseño en el navegador para así poder adaptar mas fácil el diseño a la imagen y hacer que coincidan 100%, porfa instálatela e intenta maquetar con ella así nos ahorramos muchas revisiones innecesarias. https://chrome.google.com/webstore/detail/perfectpixel-by-welldonec/dkaagdgjmgdmbnecmcefdhjekcoceebi?hl=en

**Comment by RJ64** [comment]
Revisaré el plugin. 

Está todo corregido salvo lo primero que me pones. No termino de saber a qué te refieres con lo del tamaño y color del email y contador
El icono de borrar ni lo había visto. Ya está puesto

**Comment by tavi004** [comment]
A estos 2 textos me refiero. Que tienen que tener 13px tamaño, bold #717171 
Y el contador igual, que esté gris y en estado activo se ponga en azul tanto el texto del mail como el contador
![image](https://user-images.githubusercontent.com/3248361/34248526-c23556d8-e636-11e7-9a52-6a397d0f56d9.png)


El icono sale estirado, no es el tamaño real de la imagen. El icono tiene que ser 14x14px
![image](https://user-images.githubusercontent.com/3248361/34249087-aebb2374-e638-11e7-9f3e-e2544aa332b1.png)

**Comment by RJ64** [comment]
Modificado

**Comment by jorge9200** [comment]
@RJ64 cuando termines una issue o vuelva a nuestro lado por favor reasigna la issue a su correspondiente (en este caso @tavi004, si no sabes a mi)

**Comment by jorge9200** [comment]
si no es imposible estar pendientes de que issues estan en nuestro tejado.

**Comment by tavi004** [comment]
Ya está casi, solo faltaría el tamaño del numero de correo sin leer que sea 13px tambien y #717171 y alinearlo bien a la derecha:
![image](https://user-images.githubusercontent.com/3248361/34302851-0c8235c4-e733-11e7-853e-510d837eb92a.png)

**Comment by RJ64** [comment]
Hecho. No estaban alineados porque no estaba pensado para que hubiese más de 1000 sin leer. Lo hemos agrandado un poco

**Comment by tavi004** [comment]
perfecto!
