### ISSUE TITLE
Error de counter en correos eliminados

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#20]
Al borrar un email de la carpeta de emails eliminados, el email desaparece correctamente pero el counter de emails (no leidos) de la carpeta de correos eliminados suma una unidad en vez de restarla.

![outlook1](https://user-images.githubusercontent.com/26099829/35057957-c3b5a6bc-fbb6-11e7-88cb-18fba0681849.png)
![outlook2](https://user-images.githubusercontent.com/26099829/35057959-c5a0ddd4-fbb6-11e7-9f74-fbbe07035b5c.png)

**Comment by RJ64** [comment]
Solved
