### ISSUE TITLE
Peticion de addAttachments ANTES de seleccionar el archivo.

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Outlook#21]
Cuando pulsas sobre el boton "Adjuntar" a nuestro backend llega una petición de adjuntar con un FSNodeId vacío. Esta petición sobra.

Cuando seleccionas un archivo se vuelve a invocar addAttachments con el archivo especificado en "Adjuntar" (esta invocacion es la correcta)

**Comment by RJ64** [comment]
Done. Alguna cosa que se me quedaría por ahí
