### ISSUE TITLE
El autoguardado se realiza por intervalo de tiempo y no cuando se modifica el correo (con una pequeña espera)

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Outlook#22]

**Comment by icastillejogomez** [comment]
Esto también provoca llamadas recursivas a "getFolders".

**Comment by RJ64** [comment]
Cambiado a que sea cuando el tinymce detecta un cambio

Las llamadas a getFolders es porque al autoguardar, hotmail manda un evento con taaanta información que no me queda otra más que investigar si el evento ha sido un marcar/desmarcar correo como leido y hay que actualizar las badges

**Comment by javiergarmon** [comment]
Una propuesta que te hago: autoguardado con delay e intervalo "inteligente".

```js
var interval = 0
var hasChanges = false

var save = function(){
  hasChanges = false
  // Do your magic here
}

// Please, change this to the real TinyMCE event
tinymce.on( 'change', function(){
  hasChanges = true
  clearTimeout( interval )
  interval = setTimeout( save, 2 * 1000 )
})

setInterval( function(){
  if( hasChanges ){
    save()
  }
}, 30 * 1000 )
```

**Comment by RJ64** [comment]
Gracias @javiergarmon . Hecho.

**Comment by icastillejogomez** [comment]
Cumple la funcionalidad. Cierro.
