### ISSUE TITLE
Al añadir un adjunto en modo Redactar, el adjunto se comporta como si fuera un adjunto ya enviado

### ISSUE THREAD

**Issue by javiergarmon** [Inevio/Outlook#23]
![captura de pantalla 2018-01-18 a las 13 12 06](https://user-images.githubusercontent.com/1794673/35097655-5f757114-fc51-11e7-9ef0-c5ae5723f8b2.png)

Solo deja descargar o guardar en horbito, debería simplemente ofrecer las opciones de "Abrir" y de "Borrar del mensaje"

**Comment by RJ64** [comment]
Cómo lo abro?

**Comment by RJ64** [comment]
No lo puedo desatachear. No función

**Comment by javiergarmon** [comment]
> Cómo lo abro?

Una vez que tienes el FSNode (el objeto que te viene con el nombre y esas cosas) le haces `.open()` y ya está 😄

**Comment by RJ64** [comment]
Listo

**Comment by icastillejogomez** [comment]
Listo, la opción de abrir la descartamos al final por suponer mucha complejidad. Elimina esa opción y listo. Cierro.
