### ISSUE TITLE
Si el archivo que se intenta añadir pesa mas de 4MB se debe añadir como enlace

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Outlook#24]
Outlook tiene un limite en sus peticiones REST de 4MB y de ahí el límite. [Add attachment docs.](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_post_attachments) Como me estas pasando el id del FSNode, es parecido a como deciamos del open pero sin tantas complicaciones. 

![image](https://user-images.githubusercontent.com/16567802/35115621-24574976-fc89-11e7-8ce4-1262628f72d5.png)

La idea sería preguntar al usuario si lo desea adjuntar como una url. No se si tienes Gmail instalado pero sería replicar el proceso. 

![image](https://user-images.githubusercontent.com/16567802/35115829-c3532a2c-fc89-11e7-861c-c2d64bd2812e.png)

Es muy sencillo. Para abrir un cuadro de dialogo lo que tienes que hacer es:

![image](https://user-images.githubusercontent.com/16567802/35115936-084cf2d4-fc8a-11e7-8990-843f298f3ecd.png)

**Comment by RJ64** [comment]
Hecho. Lo que no estoy muy seguro es de los textos...

**Comment by icastillejogomez** [comment]
a que te refieres con los textos? :smile:

**Comment by icastillejogomez** [comment]
Confirmo que se "bloquea/detiene" el adjuntado de un archivo mayor a 4MB. Pero en ningún momento me pregunta si deseo link y después de una confirmación mía lo añada al contenido del cuerpo del mensaje.

**Comment by RJ64** [comment]
Sí ques salen pero hasta que no se ha subido del todo. Ya se ha modificado para que compruebe el tamaño antes de adjuntarlo

**Comment by icastillejogomez** [comment]
Sigo sin verlo. Te dejo un video: http://wz.io/f/29Y1LfZE

Cuando el usuario selecciona sus archivos con el selectSource de api FS te devuelve un array con ids, como ya sabrás. 
Si haces ` api.fs( fsNodeId, ( err, fsNodeData ) => { console.log( fsNodeData.size ) } ) `

Deberías obtener el tamaño y comprobar si es mayor o menos al máximo establecido. Confirmo que en mi caso, ahora mismo hace 10 minutos, al subir el archivo de mas de 1GB se ha puesto a subirlo y ahora hace escasos minutos por fin me ha dado el error porque han fallados todas la conexiones por timeouts. 

Ya me cuentas.

**Comment by RJ64** [comment]
Justo el arrastre no había caido y no estaba implementado. Ya está listo

**Comment by icastillejogomez** [comment]
Cuando haces click va bien, pero con drag a drop creo que no envias el id. Definitivamente no funciona ya que devuelve un error BAD_PARAMS

**Comment by RJ64** [comment]
Solucionado. Ha sido por el api.fs que he iontroducido para averiguar el peso. No hice las pruebas cuando pesaba menos de 4MB.
