### ISSUE TITLE
Al enviar un correo se mandan demasiados intros

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Outlook#26]
Es es el correo en la ventana de redactar:

![image](https://user-images.githubusercontent.com/1384919/35149114-395f2262-fd15-11e7-956c-7a8c540b2aac.png)

Este es el correo tal y como se ve en Gmail:

![image](https://user-images.githubusercontent.com/1384919/35149134-4878e166-fd15-11e7-9874-05c5640c0ae9.png)

**Comment by RJ64** [comment]
Solucionado. Ahora es más representativo

**Comment by Robby2023** [comment]
El problema no es a la hora de representarlo en el TinyMCE sino en eliminar esos dobles intros. Ahora no puedo enviar mensajes con intros o sino se ven así:

![image](https://user-images.githubusercontent.com/1384919/35273327-7e09d382-0038-11e8-86e4-daa0f44c75d3.png)

Así es como se debería de ver:

![image](https://user-images.githubusercontent.com/1384919/35273364-a1a84a80-0038-11e8-83c7-5fa2a32fd296.png)

Según cómo funciona ahora mismo la app no puedo enviar mensajes con intros o sino se van a ver así de raros al recibir el correo.

**Comment by RJ64** [comment]
@Robby2023 Sé lo que dices pero ahora la representación se corresponde más fielmente a cómo se va a ver en la recepeción. Si quieres meterle dos intros en un correo vas a ver cuando lo estés creando el espacio que habrá entre un párrafo y el siguiente y será lo que recibe el receptor. Si quieres menos espacio le metes solo un enter

![creando](https://user-images.githubusercontent.com/2165183/35274046-ecf58c26-003a-11e8-9d3e-cbed5da92de1.jpg)

![resultado](https://user-images.githubusercontent.com/2165183/35274057-f799176a-003a-11e8-8db5-6eb8d9fdca1b.jpg)

**Comment by Robby2023** [comment]
De acuerdo
