### ISSUE TITLE
Los correos tardan mucho en enviarse

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Outlook#29]
Actualmente cuando escribes un nuevo correo y le das a enviar, tarda mucho en cerrarse la ventana, debería de ser instantáneo. Si es porque se está esperando la respuesta de confirmación por parte de Microsoft, lo suyo sería lanzar un banner diciendo "Correo enviado" cuando haya confirmación y si hay algún error soltarlo también por el banner.

**Comment by RJ64** [comment]
¿Y qué hacemos? ¿Según le des al botón de enviar volvemos a la carpeta donde estuviera y el usuario se queda sin saber si se ha enviado o no o qué hasta que se envíe y le mostramos una alerta con el resultado? En un primer momento se quedaría un poco perdido sin saber si se ha enviado o no y la alerta de enviado o error lo recibiría a lo mejor cuando está haciendo otras cosas. Tampoco lo veo como solución pero lo que me digáis

**Comment by Robby2023** [comment]
La solución es mandar al usuario a la carpeta al darle al botón de enviar y lanzar un popup cuando se haya enviado correctamente o lanzar un popup diciendo que ha habido un error si ocurre.

**Comment by RJ64** [comment]
Hecho

**Comment by Robby2023** [comment]
Ahora mismo estás lanzando un alert cuando el correo se manda correctamente. En su lugar deberías lanzar un banner, @jorge9200 te pasa la docu

**Comment by jorge9200** [comment]
Toma este como ejemplo
![image](https://user-images.githubusercontent.com/8724844/35514216-c2c5d422-0505-11e8-960e-10c5b01a657f.png)

**Comment by jorge9200** [comment]
pero en vez de 522 usa 521

**Comment by jorge9200** [comment]
a

**Comment by RJ64** [comment]
done

**Comment by jorge9200** [comment]
fix
