### ISSUE TITLE
El campo de redacción de correo debería ampliarse con la ventana

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Outlook#30]
Actualmente si tengo la ventana pequeña y le doy a nuevo correo, si decido ampliar en ese momento la ventana el campo para redactar el correo no se amplía junto con la ventana (en ancho si, en alto no):

![image](https://user-images.githubusercontent.com/1384919/35150432-a84bd648-fd1a-11e7-9634-dfa0e4a8274a.png)

**Comment by RJ64** [comment]
No tengo la forma de saber si se redimensiona la ventana. ¿Tenéis algún evento así?

**Comment by Robby2023** [comment]
No me reasignes cada vez que tengas una pregunta, menciona a la persona a la que haces la pregunta y listo. Por ejemplo @icastillejogomez o @jorge9200

**Comment by RJ64** [comment]
Done
