### ISSUE TITLE
Cuando le doy a nuevo correo debería poner el foco del cursor en el "To"

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Outlook#31]
Sería muy cómodo que al darle a nuevo correo te pusiese el foco del cursor en el campo de "To" porque lo primero que tienes que hacer cada vez que le das a nuevo correo es hacer click en ese campo para escribir.

**Comment by RJ64** [comment]
Hecho

**Comment by Robby2023** [comment]
Perfe
