### ISSUE TITLE
El "To" debería ser un label del input

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Outlook#32]
Cuando estoy escribiendo un correo, si quiero cambiar los destinatarios, sin querer muchas veces le doy al "To" porque me creo que eso va a activar el input para escribir pero sin embargo resulta que tengo que hacer click un poco hacia la derecha que es donde de verdad está el input.

**Comment by RJ64** [comment]
No es así como funciona outlook, el to no es un label. Lo que si hemos hecho es que al hacer click en el To se focuse en el input

**Comment by Robby2023** [comment]
Eso es exactamente lo que quería, perfect
