### ISSUE TITLE
Función de <Borrar Emails> al seleccionar checkboxes no funciona bien

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#33]
Cuando selecciono uno o mas correos mediante sus "checkboxes" y presiono <Borrar Emails> los emails se eliminan pero si recargo Horbito, vuelven a aparecer en la bandeja de entrada.

Borrarlos mediante el icono de la papelera o mediante Mover a -> Elementos Eliminados funciona bien.

**Comment by Alb3niz** [comment]
Hemos investigado y parece ser que al realizar el moveMessage al clicar sobre Delete Mails no esta moviendo el mail realmente, xq realizando el handle del callback de la petición

![image](https://user-images.githubusercontent.com/26099829/35158585-cd94d374-fd37-11e7-8ac5-c120ae9e7ece.png)

![image](https://user-images.githubusercontent.com/26099829/35158592-d1b580de-fd37-11e7-8270-5ca5e01414aa.png)

hemos averiguado que esta dando un error:

![image](https://user-images.githubusercontent.com/26099829/35158354-1b5f8410-fd37-11e7-8dc4-cb8053755e70.png)

investiga un poco a ver que quiere decir este error y si estas pasando algo mal por parámetro.

**Comment by RJ64** [comment]
Listo

**Comment by Alb3niz** [comment]
Perfecto! Cierro Issue.
