### ISSUE TITLE
Tratamiento incorrecto de errores

### ISSUE THREAD

**Issue by icastillejogomez** [Inevio/Outlook#34]
Me he estado fijando y hay veces que tratas los errores de forma erronea. Al adjuntar un correo (debido a un fallo en un test que estoy haciendo como te he comentado) recibo un error "SERVER UNVAILABLE" y outlook me pregunta que si quiero añadir el archivo como enlace porque pesa más de 4MB. 

Por norma general, y si @javiergarmon no dice lo contario, ante un error el programa se detiene por completo ya que todas las llamadas que haces al API son 100% necesarias. 

¿A qué me refiero con eso? Cuando en una callback recibes como parámetro ( err, res ) err, es decir, no recibes res: el programa se detiene y muestra el error. (¿Imprimiendo err o o un mensaje hardcoeado @javiergarmon ?

Salvo en casos como ahora que la conectividad entre servidores ha fallado por mi test, todas las llamadas al API deberían ser correctas tanto por back-end como front-end y de llevar un error lo deberían llevar en el parámetro REST para poder distinguir que err es cosa de Horbito, como ahora fallo de conectividad en nuestros sistemas.

**Comment by RJ64** [comment]
Lo hemos modificado para que todos los errores den un alert con un mensaje de error. Decídme finalmente lo que queréis que ocurra y lo hacemos

**Comment by icastillejogomez** [comment]
En un principio el mensaje que ya pones mas la variable err.

**Comment by RJ64** [comment]
Ok

**Comment by icastillejogomez** [comment]
http://wz.io/f/kVv5pBez

**Comment by RJ64** [comment]
Solucionado
