### ISSUE TITLE
Copiar y Pegar en TINYMCE

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#35]
1 - Dentro del editor de texto, al hacer click derecho, no da la posibilidad de copiar y pegar. Nosotros usamos cmd + V / C pero un usuario de a pie seguramente eche de menos esta opcion. A ver si puedes investigar si TINYMCE soporta esta caracteristica. Si no pues nada.

**Comment by Alb3niz** [comment]
Vale ya veo la opcion de pegar pero cuando pego me dice que mi browser no soporta la funcion acceder a mi clipboard.

![screen shot 2018-01-26 at 11 37 18](https://user-images.githubusercontent.com/26099829/35436350-5d86f3e4-028e-11e8-8744-09311b10a9bd.png)

**Comment by RJ64** [comment]
En algunos navegadores no funciona. Al editor de documentos de Google Drive también le pasa

![screenshot-2018-1-26 121html html](https://user-images.githubusercontent.com/2165183/35437391-816db3ca-0292-11e8-9de3-f3109aa51a99.png)

**Comment by RJ64** [comment]
Como queráis, lo dejamos o lo quitamos

**Comment by Alb3niz** [comment]
Vale perfect. Hable con Javi y me dijo que mejor lo dejamos asi como esta ahora. Que de la opcion pero que tambien se vea el error que dice lo que tienes que hacer. Cierro.
