### ISSUE TITLE
Eliminar acciones en edición de texto

### ISSUE THREAD

**Issue by saragsc** [Inevio/Outlook#36]
¿Sería posible eliminar las siguientes acciones que se pueden hacer desde view? 
Visual aids, 
show invisible characters 
show bloks. 

Preview es muy útil, sin embargo está también en file. ¿podemos quitarlo de file y dejarlo solo en view?

**Comment by RJ64** [comment]
Puedo quitar show invisible characters y show bloks pero no puedo quitar visual aids ni escoger dónde se muestra preview
