### ISSUE TITLE
Capturar evento al añadir cuenta

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Outlook#39]
Hemos añadido un evento q se dispara cuando metes una nueva cuenta. Falta mertelo cuando estas en login (no tienes cuentas) e introduces tu primera cuenta y al añadir cuenta dentro de la vista de correos.
```
api.integration.outlook.on('added-account', function (acc) {
  api.integration.dropbox(acc.id, function(err, account){
    if(err) return handleError(err)
    addCloudAccount(account)
  })
})
```

**Comment by RJ64** [comment]
Solventado. Faltaba una cosa por lo de start.js

**Comment by jorge9200** [comment]
fenomeno
