### ISSUE TITLE
Hay ocasiones en los que los badges no coinciden con el numero de correos sin leer de la bandeja

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Outlook#4]

**Comment by jorge9200** [comment]
![image](https://user-images.githubusercontent.com/8724844/33173855-fee287b4-d055-11e7-80e7-7caa81f18526.png)

**Comment by jorge9200** [comment]
![image](https://user-images.githubusercontent.com/8724844/33174235-735ca10a-d057-11e7-9de4-765ec831ecc0.png)

**Comment by RJ64** [comment]
En principio solucionado. Aunque igual deberíais revisar los eventos. Hay a veces que no los estoy recibiendo o tarda mucho en recibirlos

**Comment by jorge9200** [comment]
lo cierro hasta que se replique o quede fixed
