### ISSUE TITLE
abrir mail filtrado por palabra

### ISSUE THREAD

**Issue by saragsc** [Inevio/Outlook#43]
Cuando se busca un mail que contenga cierta palabra, tras la búsqueda no se puede abrir ningún mail.
He buscado por la palabra factura, me enseña todos los mails que contienen la palabra y al pulsar en cualquiera de ellos para abrir, no lo hace.

**Comment by RJ64** [comment]
Solucionado

**Comment by Alb3niz** [comment]
Perfect, cierro.
