### ISSUE TITLE
[Poco Importante] Espera durante la busqueda de emails

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#45]
Mientras se espera a que aparezcan los resultados de la busqueda esto es lo que se ve:
 
![screen shot 2018-02-13 at 15 27 52](https://user-images.githubusercontent.com/26099829/36154691-88db6460-10d2-11e8-80fb-15de77ecb2cd.png)

Quizas se podria poner una imagen tipo loading o algo... aunque sea un "Loading..."

**Comment by RJ64** [comment]
Ya tiene el mismo mensaje que entrando en una carpeta

**Comment by Alb3niz** [comment]
Perfecto cierro!
