### ISSUE TITLE
Error en busqueda de emails cuando se usa algun caracter que no sea una letra.

### ISSUE THREAD

**Issue by Alb3niz** [Inevio/Outlook#46]
Solo se pueden usar letras o espacios. Cuando se usan caracteres de tipo @ , . _ - ! sale el error de Object Object.

**Comment by RJ64** [comment]
Solucionado. Se filtra de lo que escriba y solo se buscan los caracteres y números

**Comment by Alb3niz** [comment]
Cierro.
