### ISSUE TITLE
Cuando eliminas un correo deberia incrementar el badge en correos eliminados? 

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Outlook#6]
No lo hace, aparece dentro al refrescar la bandeja pero como si estuviese "leido"

**Comment by jorge9200** [comment]
lo mismo cuando lo archivas

**Comment by RJ64** [comment]
Creo que está solucionado.
Cuando borras un correo sin leer se incrementa en Trash y decrementa en la carpeta donde estuviera. Igual con Archive. ¿Era eso a lo que te referías no?

**Comment by jorge9200** [comment]
solo los correos no leidos incrementan el badge de la bandeja de eliminados. Cuando eliminas un correo ya leido no incrementa el badge, ¿es el comportamiento habitual de outlook?

**Comment by RJ64** [comment]
El badge de eliminados es igual que inbox, son el número de correos sin leer por tanto solo se incrementa si eliminas uno no leido

**Comment by jorge9200** [comment]
es cierto, sorprendentemente ese es el comportamiento esperado, cierro
