### ISSUE TITLE
Cambios diseño 1

### ISSUE THREAD

**Issue by tavi004** [Inevio/Outlook#7]
# Header

- [x] El header tendría que ser 3px mas alto (51px)
- [x] Hay un borde-bottom que no debería estar
- [x] El logo no está bien, usa esta imagen: [logo-outlook.zip](https://github.com/Inevio/Outlook/files/1499896/logo-outlook.zip)

# Sidebar

- [x] El search bar debería tener una altura de 40px
- [x] Usa la lupa del sprite
- [x] La anchura del sidebar debería ser de 222px
- [x] A la derecha de la flecha añadir un titulo de Foder/Carpetas como en el outlook original
- [x] El icono de añadir carpeta debería aparecer en cuanto haces hover sobre el sidebar como en outlook.com
- [x] Si una carpeta no tiene correos no mostrar ningún número en vez de 0
- [x] El avatar y nombre deberían estar 14px separados a la izq y arriba
- [x] Para esta parte habría que hacer un par de cambios de funcionalidad:![image](https://user-images.githubusercontent.com/3248361/33213054-162f72ee-d126-11e7-841c-6f7b61e8985a.png)
- [x] debería aparecer el titulo de "Cuentas/Accounts" porque no se sabe muy bien que es esa zona
- [x] Debería aparecer la cuenta en la que estás actualmente y si tienes mensajes un badge
- [x] El "+" de añadir cuenta debería estar visible siempre
- [x] El color del separador debería ser: #d8d8d8

# Toolbar

- [x] Los iconos no son los del Sprite
- [x] Faltan todos los textos a la derecha de los iconos

# Inbox

- [x] En el inbox, el tamaño del texto de los mails debería ser de 13px no 15px
- [x] Si un correo está leído, el asunto sigue saliendo en bold, debería salir en normal
- [x] Como separador entre el asunto y el contenido debería haber un circulo de 4px color #9a9aa2

# Inside mail

- [x] El asunto debería estar en 21px font-weight: 900
- [x] Falta el fondo azulito sobre el boton de responder y el label
![image](https://user-images.githubusercontent.com/3248361/33213843-a0474940-d129-11e7-80ab-372dd82f1e66.png)![image](https://user-images.githubusercontent.com/3248361/33213849-a9f26e52-d129-11e7-8a53-21fef8cdac12.png)

- [x] El toolbar dentro de un mail no se parece, faltan labels y los iconos no son los del sprite
![image](https://user-images.githubusercontent.com/3248361/33213896-d6ce0a6c-d129-11e7-85fc-c077457d287e.png)![image](https://user-images.githubusercontent.com/3248361/33213928-f8780e88-d129-11e7-9a6c-3e94e364b7aa.png)

**Comment by RJ64** [comment]
Revisa de nuevo. Los textos no sé por qué no te aparecieron pero están. Faltaría hacer uso de los sprites

**Comment by tavi004** [comment]
Los textos no salen si la plataforma está en ingles, he cambiado ahora a español y si que salen. Se deberían meter también para la vers en ingles.

También te dejo por aquí el sprite de los iconos porque no se si te lo pasé. Si no te lo llegué a pasar y lo necesitas porfa pídemelos, todo lo que necesites
![sprite-outlook](https://user-images.githubusercontent.com/3248361/34213158-b2b3de70-e59e-11e7-83a3-089e25630d2f.png)
![sprite-outlook 2x](https://user-images.githubusercontent.com/3248361/34213159-b2de7248-e59e-11e7-917d-64aee539517b.png)

**Comment by RJ64** [comment]
En principio ya está solucionado todo lo que pedís aquí. Lo del inglés no sé qué decirte. En principio está bien. Tenemos tanto la versión española como la de inglés aunque nos dijo @jorge9200  que no era necesario. Los archivos es.json y en.json son iguales cambiando los textos con lo que no sabría por qué no funciona.

**Comment by jorge9200** [comment]
Aquí solo faltaria tener los textos bien traducidos? Eso lo podemos hacer nosotros. Si quieres pasame el es.json y te devuelvo el en.json bien traducido.

**Comment by tavi004** [comment]
Los iconos no están centrados con los textos

![image](https://user-images.githubusercontent.com/3248361/34248387-2fe2aaec-e636-11e7-8232-fce2b1cf3f4c.png)

El puntito separador tampoco está centrado con el texto, bajalo unos pixeles.
![image](https://user-images.githubusercontent.com/3248361/34248438-577ba1e4-e636-11e7-8a78-8e71384e9935.png)

Los contextuales no salen bien, deberian salir como el de responder
![image](https://user-images.githubusercontent.com/3248361/34248479-882c8592-e636-11e7-9562-dd4f1b00669c.png)
![image](https://user-images.githubusercontent.com/3248361/34248485-8e917af0-e636-11e7-8258-a215ab60e505.png)
![image](https://user-images.githubusercontent.com/3248361/34248488-92c2c412-e636-11e7-9c37-12d9ce2e5229.png)

**Comment by RJ64** [comment]
Vuelve a probar porque no se ve así. He probado en firefox y chrome

![header](https://user-images.githubusercontent.com/2165183/34261927-14289d9a-e66b-11e7-95c0-8300da90fa5f.jpg)
![punto](https://user-images.githubusercontent.com/2165183/34261934-1a7ede7a-e66b-11e7-8bab-1bfe88ef0f5a.jpg)

**Comment by RJ64** [comment]
@jorge9200 Si lo tenemos hecho. Tenemos en.json:

{

    "welcomeTextLine1" : "Access your email directly from horbito.",
    "welcomeTextLine2" : "You can attach and download files directly to your account without ever needing to download them.",
    "loginOutlook"  : "Log in"
    
    "search" : "Search mails...",
    "folders" : "Folders",
    "accounts" : "Accounts",
    "send" : "Send",
    "attach" : "Attach",
    "discard" : "Discard",
    "closeEmail" : "Close mail",
    "new" : "New",
    "markAllRead" : "Mark all as read",
    "reply" : "Reply",
    "replyAll" : "Reply All",
    "forward" : "Forward",
    "deleteMail" : "Delete mail",
    "archive" : "Archive",
    "spam" : "Spam",
    "markRead" : "Mark as Read",
    "markUnread" : "Mark as Unread",
    "undo" : "Undo",

    "to" : "To",
    "subject" : "Add a subject",
    "addMessagePlaceholder" : "Add a message",
    "downloadPC" : "Download",
    "downloadHorbito" : "Save in Horbito",
    "uploadPC" : "From computer",
    "uploadHorbito" : "From Horbito",
    "resultsSearch" : "Results for",
    "draft" : "Draft",
    "drafts" : "Drafts"

}

y es.json:


{

    "welcomeTextLine1" : "Access your email directly from horbito.",
    "welcomeTextLine2" : "You can attach and download files directly to your account without ever needing to download them.",
    "loginOutlook"  : "Log in",
    
    "search" : "Buscar correo...",
    "folders" : "Carpetas",
    "accounts" : "Cuentas",
    "send" : "Enviar",
    "attach" : "Adjuntar",
    "discard" : "Descartar",
    "closeEmail" : "Cerrar correo",
    "new" : "Nuevo",
    "markAllRead" : "Marcar todo como leido",
    "reply" : "Responder",
    "replyAll" : "Responder a todos",
    "forward" : "Reenviar",
    "deleteMail" : "Eliminar correo",
    "archive" : "Archivar",
    "spam" : "Spam",
    "markRead" : "Marcar como leido",
    "markUnread" : "Marcar como no leido",
    "undo" : "Deshacer",

    "to" : "Para",
    "subject" : "Escribe un asunto",
    "addMessagePlaceholder" : "Escribe el mensaje",
    "downloadPC" : "Descargar",
    "downloadHorbito" : "Guardar en Horbito",
    "uploadPC" : "Desde el ordenador",
    "uploadHorbito" : "Desde Horbito",
    "resultsSearch" : "Resultados de",
    "draft" : "Borrador",
    "drafts" : "Borradores"

}

No entiendo por qué no carga el inglés cuando está igual

**Comment by tavi004** [comment]
A mi me siguen saliendo los contextuales como en la imagen, no se por que... si estoy usando chrome.

Y todavía me falta que arregles lo de los iconos, centrarlos.

**Comment by jorge9200** [comment]
a simple vista se ve, falta una coma detras del "Log in"
![image](https://user-images.githubusercontent.com/8724844/34298462-488b705e-e71e-11e7-91c6-5ba90a72c9bd.png)

**Comment by jorge9200** [comment]
Arregla lo del idioma y lo ultimo q falta de diseño y la cerramos! :)

**Comment by RJ64** [comment]
Solucionado lo del idioma. @jorge9200 bien visto, no fui capaz de verlo. 

@jorge9200 tú lo ves como @tavi004  o como se debería? No sé qué decirte, ahora mismo no lo puedo mirar en otros ordenadores. De todas maneras, lo que dices de centrar los iconos no sé, en la imagen que te he pasado para mí se ven centrados. Si me dices cuánto bajarlos lo hacemos

**Comment by tavi004** [comment]
Vale pues vamos con la barra de herramientas. 

- [x] Primero cambiar la fuente a Lato 13px y letter-spacing: 0.02em

- [x] Centrar bien los textos

- [x] Baja 1px todos los iconos, menos el de responder ![image](https://user-images.githubusercontent.com/3248361/34519989-111b67ce-f087-11e7-973d-eceead85f15b.png)

- [x] Bajar este icono 2px![image](https://user-images.githubusercontent.com/3248361/34520227-1aa7f43c-f088-11e7-8fa2-2c037b3a4d22.png)

- [x] Reducir esta linea 1px en longitud para que se centre bien ![image](https://user-images.githubusercontent.com/3248361/34520455-fde242b6-f088-11e7-900d-e6fee2a9ebd3.png) y bajar 1px la flechita

**Comment by RJ64** [comment]
En principio está todo lo que comentas hecho pero lo de la longitud en el responder (el último punto) en inglés por ejemplo, la palabra es mucho más pequeña y quedaba fatal. Lo que he hecho ha sido quitar el width que se adapte al texto de dentro. Dime lo que opinas

**Comment by tavi004** [comment]
Ok esta issue la veo guay, la cierro y en cuanto haga otra revisión a otras vistas te creo otra issue.
