### ISSUE TITLE
Me tarda siglos en listar los correos

### ISSUE THREAD

**Issue by Robby2023** [Inevio/Outlook#8]
He grabado un video en el que se ve que GMail no tarda casi pero que Outlook me tarda siglos en listar los correos. Mando el video por el grupo de Telegram.

**Comment by RJ64** [comment]
Lo he estado revisando. Esto es lo que se lleva a cabo: Se listan las cuentas de correo del usuario, de la primera (la principal), solicitamos las carpetas y de la carpeta de inbox los 50 primeros correos. No sabría deciros por qué a todos tarda algo normal y a tí te tarda tanto. Nosotros no hacemos nada diferente

**Comment by Robby2023** [comment]
@icastillejogomez lo hemos estado mirando y efectivamente se queda parado en las funciones "getFolders" y sobretodo en "getMessagesInFolder", ¿puedes revisar esas funciones a ver por qué están tardando tanto?

**Comment by RJ64** [comment]
Es de vez en cuando. Yo por mi experiencia no me sorprendería que fuese hotmail el problema. Que tiende a tardar a veces

**Comment by icastillejogomez** [comment]
> outlookGetFolders - MS Request: 598.047ms
> outlookGetFolders: 604.829ms
> outlookGetFolders - MS Request: 221.234ms
> outlookGetFolders: 223.219ms

> outlookGetMessagesInFolder - MS Request: 7829.130ms
> outlookGetMessagesInFolder: 7831.429ms

no se puede hacer nada, el 98.87% (en el primer caso)  se lo pasa esperando a que MS responda... y vamos viendo los demás son todos de este estilo..

**Comment by Robby2023** [comment]
Le he pedido a @tavi004 que nos haga diseño de cargando para mostrarse mientras se están listando los correos

**Comment by tavi004** [comment]
![image](https://user-images.githubusercontent.com/3248361/35147437-e3b171c2-fd0e-11e7-98f4-91669cc9cdb2.png)
El texto  lato 21px bold #9a9aa2
Assets: ![server-icon](https://user-images.githubusercontent.com/3248361/35147498-17c23618-fd0f-11e7-8753-e36734a51669.png)![server-icon 2x](https://user-images.githubusercontent.com/3248361/35147499-17dfadba-fd0f-11e7-9c58-fac865a39d7c.png)

**Comment by RJ64** [comment]
Listo

**Comment by tavi004** [comment]
A mi me sale el retina y estoy en pantalla normal (el pequeño es para normal y el grande retina)

**Comment by jorge9200** [comment]
y para el tema del icono en retina nosotros usamos esta media query de css:
![image](https://user-images.githubusercontent.com/8724844/35514366-41079a5a-0506-11e8-96ee-7436914db48b.png)

**Comment by RJ64** [comment]
Hecho

**Comment by jorge9200** [comment]
fix
