### ISSUE TITLE
Implementar drag & drop para attachments

### ISSUE THREAD

**Issue by jorge9200** [Inevio/Outlook#9]
Cuando estas en la vista de nuevo correo. Deberías poder hacer drag & drop desde nuestro Files a tu aplicación y hacer la asignación del attachment.

Actualmente se esta implementando para gmail, aqui la issue para ver como hacerlo:
https://github.com/Inevio/Gmail/issues/3

**Comment by RJ64** [comment]
En principio implementado pero está fallando la función addAttachment con lo que no lo he podido comprobar. Echad un vistazo a esa función y a ver si tira

**Comment by jorge9200** [comment]
si depende de la resolucion de addAttachment() por nuestro lado, dejo asignada a @icastillejogomez, para que la desbloquee cuando se solucione el problema en cuestion

**Comment by icastillejogomez** [comment]
Necesito saber el error, los logs no me muestran nada.

**Comment by icastillejogomez** [comment]
Estoy desplegando una actualización que imprime con mas detalle el proceso de addAttachments

**Comment by icastillejogomez** [comment]
tienes que usar el método outlookSendMessage en vez de outlookSendMail porque sino el adjunto lo pierdes al enviarlo.

**Comment by RJ64** [comment]
Done

**Comment by icastillejogomez** [comment]
Confirmado que ahora si se envian los correos con adjuntos. ¿La funcionalidad de drag&drop esta implementada? No nos funciona drag&drop a nosotros.

**Comment by RJ64** [comment]
Cómo va a funcionar el drag&drop si habéis cambiado lo que devuelve el wz-drop?

**Comment by RJ64** [comment]
Funcionando

**Comment by icastillejogomez** [comment]
Genial, solo faltarían pequeños detalles de diseño para indicar al usuario donde soltar el archivo

![gmailissue](https://user-images.githubusercontent.com/16567802/35100750-396b958c-fc5d-11e7-8de8-b8f403c12935.png)

**Comment by RJ64** [comment]
Listo

**Comment by jorge9200** [comment]
seems good!
